= Rolling upgrades of a JGroups cluster

This document describes how to upgrade a JGroups cluster to a new, backwards-incompatible version,
or a new configuration. The term _incompatible_ means that the nodes running on the new version
(or configuration) would be unable to form a cluster with the existing nodes.

Upgrading a cluster to a new version is critical for some customers, who cannot afford downtime.

The design is influenced by how Kubernetes applies a new configuration: it adds a new pod,
running with the new configuration, then kills off an existing one, until all existing pods
have been replaced.

== Overview

Say we have a cluster `{A1,A2,A3}`. A rolling upgrade might proceed as follows:

* `{A1,A2,A3}`
* New node `B1` is started in a separate cluster: `{A1,A2,A3} {B1}`
* An existing node is killed: `{A1,A3} {B1}`
** Note that we don't know (in Kubernetes) which node is killed
* And so on:
* `{A1,A3} {B1,B2}`
* `{A3} {B1,B2}`
* `{A3} {B1,B2,B3}`
* `{B1,B2,B3}`

=== Goals

There are 2 goals for the above scenario:

. There needs to be a _global view_ of all nodes; ie. instead of the 2 separate
cluster views `{A1,A2,A3}` and `{B1}`, the global view should be `{A1,A2,A3,B1}`
. Members of the different clusters must be able to talk to each other; a.k.a. send
(unicast and multicast) messages to each other. In the above example, `A2` should be able to send
a message to `B1`.


=== Design overview

In order to achieve the above goals, all application messages are sent to a JGroups-independent
server (the _RelayServer_), which relays them to all registered cluster nodes, as shown below:

----
                    ---------------
                    | RelayServer |
                    ---------------
                           ^
                           |
                           |
        ---------------------------------
        |      |        |         |      |
        |      |        |         |      |
        v      v        v         v      v
      ----    ----    ----      ----   ----
      |A1|    |A2|    |A3|      |B1|   |B2|
      ----    ----    ----      ----   ----
----

The RelayServer


----

            Application
                 ^
                 | (send, receive)
                 |
                 |
                 v
            -----------                        ---------------
            |  RELAY3 | <------------------->  | RelayServer |
            -----------                        ---------------
            |  FRAG3  |
            -----------
            | NAKACK2 |
            -----------
            |    ...  |
            -----------


----